### Создание пользователя
POST http://127.0.0.1:3000/api/v1/user/create
content-type: application/json
authorization: token

# Необязательные поля
# first_name
# last_name
# role_id
{
    "first_name": "Bob",
    "last_name": "Marley",
    "email": "user@site.org",
    "password": "123",
    "password_confirm": "123",
    "role_id": 2
}
