POST http://127.0.0.1:3000/api/v1/user/create
content-type: application/json

{
    "first_name": "Bob",
    "last_name": "Marley",
    "email": "user@site.org",
    "password": "123",
    "password_confirm": "123"
}
