server:
  protocol: http
  url: 127.0.0.1
  port: 3000

sqlite:
  path: internal/database/sqlite.db

postgres:
  host: localhost
  port: 5432
  user: root
  password: 123456
  database: goan
  sslmode: disable

# openssl rand -base64 172 | tr -d '\ n'
jwt:
  secret: 9bt7EMA3BEu6QwRPTE4Vzwg2486U5cSlNCt0PF1YFA2Crua5hoPA2RFgeBl39OlPGMsweg5adc3KAiev3q94vLJtwRYRPbPw5
  expires: 3600
