server:
  protocol: http
  url: 127.0.0.1
  port: 3000

sqlite:
  path: internal/database/sqlite.db

postgres:
  host: localhost
  port: 5432
  user: root
  password: 123456
  database: goan
  sslmode: disable
